import os
import os.path

INC = os.path.join('include', os.getenv('HOME'), 'local-install', 'include')
LIB = os.path.join('.', os.getenv('HOME'), 'local-install', 'lib')

# First let's compile the C files
env = Environment(CPPPATH=[INC], LIBPATH=[LIB, '#', '#/build/core'], ENV=os.environ)
env.Append(CCFLAGS='-v')
env.Replace(CC= 'clang')
env.Append(CFLAGS='-Weverything -Wno-padded -pedantic -std=c99 -g')
env.Replace(CXX= 'clang++')
env.Append(CXXFLAGS='-Weverything -Wno-padded -Wno-c++98-compat-pedantic -pedantic -std=c++11 -O0 -g')

env.Program('demo_broker', env.Split('demo_main_broker.c'), LIBS=['SCALN'])
env.Program('demo_reply', env.Split('demo_main_reply.c'), LIBS=['SCALN'])
env.Program('demo_subscriber', env.Split('demo_main_subscriber.c'), LIBS=['SCALN'])
